# Generated by Django 3.0.5 on 2020-11-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, verbose_name='買ってきてほしいもの'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='summary',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
    ]
