# Generated by Django 3.0.5 on 2020-10-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
